# Generated by Django 5.1.7 on 2025-09-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_note_tags_alter_note_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated brief summary of the note content'),
        ),
    ]
